name: Oracle Cloud - Instance Provisioner

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Her 10 dakikada bir otomatik çalışır

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install

      - name: Create Private Key File
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > oracle_key.pem
          chmod 600 oracle_key.pem

      - name: Create .env on the fly
        run: |
          echo "OCI_REGION=${{ secrets.OCI_REGION }}" > .env
          echo "OCI_USER_ID=${{ secrets.OCI_USER_ID }}" >> .env
          echo "OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}" >> .env
          echo "OCI_KEY_FINGERPRINT=${{ secrets.OCI_FINGERPRINT }}" >> .env
          echo "OCI_PRIVATE_KEY_FILENAME=./oracle_key.pem" >> .env
          echo "OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}" >> .env
          echo "OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}" >> .env
          echo "OCI_OCPUS=4" >> .env
          echo "OCI_MEMORY_IN_GBS=24" >> .env
          echo "OCI_SHAPE=VM.Standard.A1.Flex" >> " .env
          echo "OCI_MAX_INSTANCES=1" >> .env
          echo "OCI_SSH_PUBLIC_KEY=\"${{ secrets.OCI_SSH_PUBLIC_KEY }}\"" >> .env

      - name: Run Provisioning Bot
        # Buraya --debug ekledik, hatayı detaylı göreceğiz
        run: php index.php --debug

      - name: Run Provisioning Bot
        run: php index.php
